[package]
name = "support-watcher"
description = "Prometheus metrics for the Helper Heidi"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
metrics = "0.24.2"
metrics-exporter-prometheus = "0.17.2"
